### ISSUE TITLE
Multiple `command` keys for script

### ISSUE THREAD

**Issue by simonsmith** [AndrewVos/pj#3]
Could we allow the `script` to take multiple commands and execute them in order?

```yaml
- script:     
    command: 
       - 'echo hello'
       - 'echo goodbye'
```

Might be easier than using the `|` for simpler things
